pages/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
]

poll_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.answers, name='answers'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('draft/', views.draft, name='draft'),
    path('create_question/', views.create_question, name='create_question'),
    path('add_answer/', views.add_answer, name='add_answer'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/models.py
from django.db import models

# Create your models here.

polls/models.py
'''
'''
from django.db import models


class Question(models.Model):
    '''
    '''
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        '''
        '''
        return self.question_text


class Choice(models.Model):
    '''
    '''
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        '''
        '''
        return self.choice_text

pages/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'pages/index.html')

polls/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .models import Question, Choice


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def answers(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/answers.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/answers.html', {
            'question': question,
            'error_message': 'Please select a choice.'})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def draft(request):
    return render(request, 'polls/draft.html')

def create_question(request):
    from django.utils import timezone
    q_text = request.POST['question_text']
    q = Question(pub_date=timezone.now(), question_text=q_text)
    q.save()
    if len(request.POST['choice_text_a']) > 0:
        choice = Choice(question=q, votes=0, choice_text=request.POST['choice_text_a'])
        choice.save()
    if len(request.POST['choice_text_b']) > 0:
        choice = Choice(question=q, votes=0, choice_text=request.POST['choice_text_b'])
        choice.save()
    for c_num in range(len(request.POST) - 4):
        if len(request.POST['choice_text' + str(c_num)]) > 0:
            choice = Choice(question=q, votes=0, choice_text=request.POST['choice_text' + str(c_num)])
            choice.save()

    return index(request)

def add_answer(request):
        return HttpResponseRedirect(reverse('polls:index'))

poll_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="{% static "polls/add_question.js" %}"></script>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http=equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
	{% include 'partials/_navbar.html' %}
	<div class="container">
	  <div class="row">
	    <div class="col-md-6 m-auto">
	      {% block content %}
	      {% endblock %}
	    </div>
	  </div>
	</div>
	{{ h }}
</body>
</html>

poll_app/templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

<div class="card text-center">
  <div class="card-body">
	  <h1>Simple Poll App</h1>
    <p>Made with Django</p>
    <a class="btn btn-dark" href="{% url 'polls:index' %}">View</a>
  </div>
</div>
{% endblock %}

poll_app/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
  <div class="container">
    <a class="navbar-brand" href="/">Russell Molimock</a>
  </div>
</nav>

poll_app/templates/polls/answers.html
{% extends 'base.html' %}
<head>
{% load static %}
<script src="{% static "/polls/add_choice.js" %}"></script>
</head>
{% block title %}{{ question.question_text }}{% endblock %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polls:index' %}">Back To Polls</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %} 
{% for choice in question.choice_set.all %}
<div class="form-check">
  <input class="choice" type="radio" name="choice" class="form-check-input"
  id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
  <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
</div>
{% endfor %}
<div class="btn btn-success btn-sm mb-3" id="add_choice">add choice</div>
<input type="submit" value="Vote" class="btn btn-primary btn-lg btn-block mt-4" />
</form>
{% endblock %}

poll_app/templates/polls/draft.html
{% extends 'base.html' %}
{% block title %}Create a Question{% endblock %}
{% block content %}
<a class="mb-3 btn btn-secondary" href="{% url 'polls:index' %}">Back To Polls</a>
<!--<h1 class="text-center mb-3">Create a Question</h1>-->

<form class="mb-5 lead card" action="{% url 'polls:create_question' %}" method="post">
{% csrf_token %}
  <input type="text" name="question_text" placeholder="ex: What is your favorite food?">
<ul class="list-group mb-5" id="choices_form">
    <li class="list-group-item">
      <label>Choice:</label>
      <input class="choice" type="text" name="choice_text_a"></input>
    </li>
    <li class="list-group-item">
      <label>Choice:</label>
      <input class="choice" type="text" name="choice_text_b"></input>
    </li>

</ul>
  <div class="btn btn-success" id="create_choice">create choice</div>
<input type="submit" id="submit">
</form>
{% endblock %}

poll_app/templates/polls/index.html
{% extends 'base.html' %}
{% block title %}Polls App{% endblock %}
{% block content %}
<a href="{% url 'polls:draft' %}" class="float-right btn btn-primary btn-sm">Add Question</a>
  <h1 class="text-center mb-3">Poll Questions</h1>
  {% if latest_question_list %}
    {% for question in latest_question_list %}
      <div class="card mb-3">
        <div class="card-body">
        <p class="lead">{{ question.question_text }}</p>
	<a href="{% url 'polls:answers' question.id %}" class="btn btn-primary btn-sm">Answer</a>
	<a href="{% url 'polls:results' question.id %}" class="btn btn-secondary btn-sm">View Results</a>
	</div>
      </div>
    {% endfor %}
  {% else %}
    <p>No polls available</p>
  {% endif %}
{% endblock %}

poll_app/templates/polls/results.html
{% extends 'base.html' %}
{% block title %}{{ question.question_text }}{% endblock %}
{% block content %}
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>
<ul class="list-group mb-5">
  {% for choice in question.choice_set.all %}
    <li class="list-group-item">
      {{ choice.choice_text }}
      <span class="badge badge-success float-right">
        {{ choice.votes }}vote{{ choice.votes | pluralize }}
      </span>
    </li>
  {% endfor %}
</ul>
<a class="btn btn-secondary" href="{% url 'polls:index' %}">Back To Polls</a>
<a class="btn btn-dark" href="{% url 'polls:answers' question.id %}">Vote again?</a>
{% endblock %}